version: 1
disable_existing_loggers: true

formatters:
  standard:
    format: "[%(asctime)s] {%(module)s:%(lineno)d} %(levelname)s %(funcName)s() - %(message)s"
    datefmt: '%H:%M:%S'

handlers:
  console:  # handler which will log into stdout
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard  # Use formatter defined above
    stream: ext://sys.stdout
  file:  # handler which will log into file
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: standard  # Use formatter defined above
    filename: /tmp/warnings.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8

root:  # Loggers are organized in hierarchy - this is the root logger config
  level: INFO
  handlers: [console]  # Attaches both handler defined above

loggers:  # Defines descendants of root logger
  basic:  # Basic logging set up
    level: INFO
    handlers: [console]
    propagate: no  # Will not propagate logs to "root" logger

  debug:
    level: DEBUG
    handlers: [console]
    propagate: no  # Will not propagate logs to "root" logger

  fileonly:  # Log solely to a log file
    level: INFO
    handlers: [file]
    propogate: no # Will not propagate logs to "root" logger
